### ISSUE TITLE
DateTimePicker in Angular error

### ISSUE THREAD

**Issue by mchallenger88** [NathanaelA/nativescript.rocks#11]
When trying to use the DateTimePicker in an Angular app, I get the following error:

 TypeError: _nativescript_core__WEBPACK_IMPORTED_MODULE_0__.Property is not a constructor
JS:     at Module.../node_modules/@nativescript/datetimepicker/ui/picker-field-base.js (file:///node_modules\@nativescript\datetimepicker\ui\picker-field-base.js:35:0)
JS:     at __webpack_require__ (file:///src\webpack\bootstrap:750:0)
JS:     at fn (file:///src\webpack\bootstrap:120:0)
JS:     at Module.../node_modules/@nativescript/datetimepicker/ui/date-picker-field.common.js (file:///node_modules\@nativescript\datetimepicker\ui\date-picker-field.common.js:1:0)
JS:     at __webpack_require__ (file:///src\webpack\bootstrap:750:0)
JS:     at fn (file:///src\webpack\bootstrap:120:0)
JS:     at Module.../node_modules/@nativescript/datetimepicker/ui/date-picker-field.js (file:///data/...
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: TypeError: Right-hand side of 'instanceof' is not an object
System.err:
System.err: StackTrace:
System.err: (file:///node_modules\@nativescript\core\ui\layouts\flexbox-layout\flexbox-layout.js:14:0)

**Comment by NathanaelA** [comment]
This issue should have been posted to the nativescript repo, not proplugins.
