### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by tangerinegit** [NathanaelA/nativescript.rocks#5]
Hello,

I just purchased a license and I had a question.  I saw in the FAQs that you track IP addresses and can suspend an account if it is used from different IPs.

I have 2 offices in town and I go back and forth from one to the other.  I also travel quite frequently, sometimes abroad.  I am the only one using the plugins, but will be accessing them from several different IPs.

How would that work in my case?  Would I run into any issues?

Thanks.

**Comment by NathanaelA** [comment]
In this case their is no issue; because your access would be serial -- i.e. not happening at the near the same time from several locations.
