### ISSUE TITLE
Team license

### ISSUE THREAD

**Issue by alexandruantonica** [NathanaelA/nativescript.rocks#6]
Hi, 
I would like to subscribe to ProPlugins but I don't quite understand the `seat` terminology for this particular service. 
We are a team of 2 developers (different countries) that are working at the same time + a CI server (some times). Are the 2 seats enough for this team? 
What about the account? If we buy a license with more than 2 seats, can we use the same account both?

**Comment by NathanaelA** [comment]
If you get a business 2 seat license, then both of you can use the same account and the CI server can also use the same account.
